:- consult('$SITLOG_HOME/apps/test_behaviors/user_functions.pl').
%:- consult('$SITLOG_HOME/apps/robocup_2015/ricardo/user_functions_arturo.pl').
%:- consult('$SITLOG_HOME/apps/robocup_2015/ricardo/RAFV_planner.pl').
%:- consult('$SITLOG_HOME/apps/robocup_2015/ricardo/user_functions_b.pl').
%:- consult('$SITLOG_HOME/apps/robocup_2015/ricardo/create_asp_from_prolog.pl').
%:- consult('$SITLOG_HOME/apps/robocup_2015/ricardo/ETR_P_User_Functions.pl').
%:- consult('$SITLOG_HOME/apps/robocup_2015/ricardo/ETR_P_Transform_DB_To_ASP.pl').
%:- consult('$SITLOG_HOME/apps/robocup_2015/ricardo/ETR_P_Preparation_For_Diagnosis.pl').
%:- consult('$SITLOG_HOME/apps/robocup_2015/ricardo/ETR_P_Diagnosis.pl').
%:- consult('$SITLOG_HOME/apps/robocup_2015/ricardo/ETR_P_Return.pl').
